name: auto copy Issues from another repository

on: [push]

env:
  DEVOPS_DIR: devops
  GHSECRET: ${{ secrets.GITHUB_TOKEN }}
  TARGET_REPO: ${{ github.repository }}
  SOURCE_REPO: bzz-fgict/M319_LU12_A03_Lottery
  SCRIPT_REPO: Modulbereich-Programmierung-Python/CopyIssues

jobs:
  show-actor:
    name: show-actor
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${GITHUB_ACTOR}
  copy-issues:
    if: ${{ contains(github.actor, 'classroom') }}
    name: CopyIssues
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyGithub
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check-out the IssueCopy Repo
      uses: actions/checkout@v2
      with:
        repository: ${{ env.SCRIPT_REPO }}
        path: ${{ env.DEVOPS_DIR }}
    - name: Copy the Issues
      run: python ${{ env.DEVOPS_DIR }}/issues.py
      shell: sh
